# Generated by Django 2.2 on 2019-04-20 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChioceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=20)),
                ('number', models.IntegerField(default=0)),
                ('is_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.IssueList')),
            ],
        ),
    ]
